# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-08-19 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baker_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='bkimg/')),
                ('answer', models.CharField(max_length=100)),
                ('hint', models.CharField(max_length=300)),
                ('level', models.IntegerField()),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
