# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-08-19 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baker_questions',
            name='name',
            field=models.CharField(default='zero', max_length=10),
        ),
    ]
