# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-09-06 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160826_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electroregistration',
            name='scity',
        ),
        migrations.RemoveField(
            model_name='electroregistration',
            name='scollege',
        ),
        migrations.RemoveField(
            model_name='electroregistration',
            name='scon',
        ),
        migrations.RemoveField(
            model_name='electroregistration',
            name='smail',
        ),
        migrations.RemoveField(
            model_name='electroregistration',
            name='sname',
        ),
        migrations.RemoveField(
            model_name='electroregistration',
            name='team',
        ),
    ]
