# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-09-06 20:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160907_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquahuntregistration',
            name='ficity',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='aquahuntregistration',
            name='ficollege',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='aquahuntregistration',
            name='ficon',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Enter a valid phone number.')]),
        ),
        migrations.AddField(
            model_name='aquahuntregistration',
            name='fimail',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aquahuntregistration',
            name='finame',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
