# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 09:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_designoregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoscopeRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(default=None, max_length=20)),
                ('fname', models.CharField(max_length=40)),
                ('fcollege', models.CharField(max_length=60)),
                ('fmail', models.EmailField(default=None, max_length=254, unique=True)),
                ('fcon', models.CharField(default=None, max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Enter a valid phone number.')])),
                ('fcity', models.CharField(max_length=12, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
