# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-09-10 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmishRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('college', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=12)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackFromAndroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=13)),
                ('mail', models.EmailField(max_length=254)),
                ('msg', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='NotifsAndroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('msg', models.TextField(max_length=200)),
            ],
        ),
    ]
