# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amishregistrations',
            name='idnum',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
