# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 19:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0003_amishregistrations_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amishregistrations',
            name='contact',
            field=models.CharField(default=None, max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='amishregistrations',
            name='mail',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
