# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0004_auto_20160913_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackfromandroid',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
